import { Poppins } from "next/font/google";
import "./globals.css";
import Credits from "./components/Credits";
import { SpeedInsights } from "@vercel/speed-insights/next";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "krd. - Kakatiya Research Day",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <SpeedInsights />
      <body className={poppins.className}>
        {children}

        <Credits />
      </body>
    </html>
  );
}
